# Generated by Django 3.0.2 on 2020-01-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.TextField(default='male'),
            preserve_default=False,
        ),
    ]
