# Generated by Django 3.0.2 on 2020-01-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_job_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
    ]
