# Generated by Django 3.0.2 on 2020-01-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_due', models.CharField(max_length=100)),
                ('role_type', models.TextField()),
                ('hire_type', models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time'), ('I', 'Intern')], max_length=1)),
                ('key_qualifications', models.TextField()),
                ('additional_comments', models.TextField()),
                ('job_location', models.TextField()),
                ('contact_info', models.TextField()),
                ('application_link', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_title', to='staff.Company')),
            ],
        ),
    ]
