# Generated by Django 3.0.2 on 2020-01-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
