# Generated by Django 3.0.2 on 2020-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_job_gender'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='savedJobs',
            field=models.ManyToManyField(to='board.Job'),
        ),
    ]
