# Generated by Django 3.0.2 on 2020-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0002_profile_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='savedCompanies',
            field=models.ManyToManyField(to='company.Company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='savedJobs',
            field=models.ManyToManyField(to='company.Job'),
        ),
    ]
